components:
  schemas:
    EnvironmentMetrics_EnvironmentMetrics:
      anyOf:
      - $ref: http://redfish.dmtf.org/schemas/v1/odata-v4.yaml#/components/schemas/odata-v4_idRef
      - $ref: http://redfish.dmtf.org/schemas/v1/EnvironmentMetrics.v1_0_1.yaml#/components/schemas/EnvironmentMetrics_v1_0_1_EnvironmentMetrics
      - $ref: http://redfish.dmtf.org/schemas/v1/EnvironmentMetrics.v1_1_1.yaml#/components/schemas/EnvironmentMetrics_v1_1_1_EnvironmentMetrics
      - $ref: http://redfish.dmtf.org/schemas/v1/EnvironmentMetrics.v1_2_0.yaml#/components/schemas/EnvironmentMetrics_v1_2_0_EnvironmentMetrics
      description: The EnvironmentMetrics schema represents the environmental metrics
        of a device.
      x-longDescription: This resource shall represent the environmental metrics for
        a Redfish implementation.
title: '#EnvironmentMetrics.EnvironmentMetrics'
x-copyright: Copyright 2014-2022 DMTF. For the full DMTF copyright policy, see http://www.dmtf.org/about/policies/copyright
x-owningEntity: DMTF
