components:
  schemas:
    OperatingConfig_OperatingConfig:
      anyOf:
      - $ref: http://redfish.dmtf.org/schemas/v1/odata-v4.yaml#/components/schemas/odata-v4_idRef
      - $ref: http://redfish.dmtf.org/schemas/v1/OperatingConfig.v1_0_2.yaml#/components/schemas/OperatingConfig_v1_0_2_OperatingConfig
      description: The OperatingConfig schema specifies a configuration that can be
        used when the processor is operational.
      x-longDescription: This resource shall represent an operational configuration
        for a processor in the Redfish Specification.
title: '#OperatingConfig.OperatingConfig'
x-copyright: Copyright 2014-2022 DMTF. For the full DMTF copyright policy, see http://www.dmtf.org/about/policies/copyright
x-owningEntity: DMTF
