components:
  schemas:
    Settings_MaintenanceWindow:
      anyOf:
      - $ref: http://redfish.dmtf.org/schemas/v1/Settings.v1_2_6.yaml#/components/schemas/Settings_v1_2_6_MaintenanceWindow
      - $ref: http://redfish.dmtf.org/schemas/v1/Settings.v1_3_4.yaml#/components/schemas/Settings_v1_3_4_MaintenanceWindow
    Settings_OperationApplyTime:
      enum:
      - Immediate
      - OnReset
      - AtMaintenanceWindowStart
      - InMaintenanceWindowOnReset
      - OnStartUpdateRequest
      type: string
      x-enumDescriptions:
        AtMaintenanceWindowStart: The requested operation is applied within the administrator-specified
          maintenance window.
        Immediate: The requested operation is applied immediately.
        InMaintenanceWindowOnReset: The requested operation is applied after a reset
          but within the administrator-specified maintenance window.
        OnReset: The requested operation is applied on a reset.
        OnStartUpdateRequest: The requested operation is applied when the StartUpdate
          action of the update service is invoked.
      x-enumLongDescriptions:
        AtMaintenanceWindowStart: This value shall indicate the requested create,
          delete, or action operation is applied during the maintenance window that
          the MaintenanceWindowStartTime and MaintenanceWindowDurationInSeconds properties
          specify.  A service can complete resets during this maintenance window.
        Immediate: This value shall indicate the requested create, delete, or action
          operation is applied immediately.
        InMaintenanceWindowOnReset: This value shall indicate the requested create,
          delete, or action operation is applied during the maintenance window that
          the MaintenanceWindowStartTime and MaintenanceWindowDurationInSeconds properties
          specify, and if a reset occurs within the maintenance window.
        OnReset: This value shall indicate the requested create, delete, or action
          operation is applied when the system or service is reset.
        OnStartUpdateRequest: This value shall indicate the requested create, delete,
          or action operation is applied when the StartUpdate action of the update
          service is invoked.
      x-enumVersionAdded:
        OnStartUpdateRequest: v1_3_0
      x-versionAdded: v1_2_0
    Settings_OperationApplyTimeSupport:
      anyOf:
      - $ref: http://redfish.dmtf.org/schemas/v1/Settings.v1_2_6.yaml#/components/schemas/Settings_v1_2_6_OperationApplyTimeSupport
      - $ref: http://redfish.dmtf.org/schemas/v1/Settings.v1_3_4.yaml#/components/schemas/Settings_v1_3_4_OperationApplyTimeSupport
    Settings_PreferredApplyTime:
      anyOf:
      - $ref: http://redfish.dmtf.org/schemas/v1/Settings.v1_1_6.yaml#/components/schemas/Settings_v1_1_6_PreferredApplyTime
      - $ref: http://redfish.dmtf.org/schemas/v1/Settings.v1_2_6.yaml#/components/schemas/Settings_v1_2_6_PreferredApplyTime
      - $ref: http://redfish.dmtf.org/schemas/v1/Settings.v1_3_4.yaml#/components/schemas/Settings_v1_3_4_PreferredApplyTime
    Settings_Settings:
      anyOf:
      - $ref: http://redfish.dmtf.org/schemas/v1/Settings.v1_0_7.yaml#/components/schemas/Settings_v1_0_7_Settings
      - $ref: http://redfish.dmtf.org/schemas/v1/Settings.v1_1_6.yaml#/components/schemas/Settings_v1_1_6_Settings
      - $ref: http://redfish.dmtf.org/schemas/v1/Settings.v1_2_6.yaml#/components/schemas/Settings_v1_2_6_Settings
      - $ref: http://redfish.dmtf.org/schemas/v1/Settings.v1_3_4.yaml#/components/schemas/Settings_v1_3_4_Settings
title: '#Settings'
x-copyright: Copyright 2014-2022 DMTF. For the full DMTF copyright policy, see http://www.dmtf.org/about/policies/copyright
x-owningEntity: DMTF
