components:
  schemas:
    Settings_v1_0_7_Settings:
      additionalProperties: false
      description: The resource settings.
      properties:
        ETag:
          description: The entity tag (ETag) of the resource to which the settings
            were applied, after the application.
          nullable: true
          readOnly: true
          type: string
          x-longDescription: This property shall contain the entity tag (ETag) of
            the resource to which the settings were applied, after the application.  The
            client can check this value against the ETag of this resource to determine
            whether the resource had other changes.
        Messages:
          description: An array of messages associated with the settings.
          items:
            $ref: http://redfish.dmtf.org/schemas/v1/Message.yaml#/components/schemas/Message_Message
          type: array
          x-longDescription: This property shall contain an array of messages associated
            with the settings.
        SettingsObject:
          $ref: http://redfish.dmtf.org/schemas/v1/odata-v4.yaml#/components/schemas/odata-v4_idRef
          description: The link to the resource that the client can PUT or PATCH to
            modify the resource.
          readOnly: true
          x-longDescription: This property shall contain the URI of the resource that
            the client can PUT or PATCH to modify the resource.
        Time:
          description: The time when the settings were applied.
          format: date-time
          nullable: true
          readOnly: true
          type: string
          x-longDescription: This property shall indicate the time when the settings
            were applied to the resource.
      type: object
      x-longDescription: This type shall describe any settings of a resource.
      x-patternProperties:
        ^([a-zA-Z_][a-zA-Z0-9_]*)?@(odata|Redfish|Message)\.[a-zA-Z_][a-zA-Z0-9_]*$:
          description: This property shall specify a valid odata or Redfish property.
title: '#Settings.v1_0_7'
x-copyright: Copyright 2014-2020 DMTF. For the full DMTF copyright policy, see http://www.dmtf.org/about/policies/copyright
x-owningEntity: DMTF
x-release: '1.0'
